-- =====================================================
-- Complete Supabase Table Structure Verification & Setup
-- =====================================================
-- Run this SQL in your Supabase SQL Editor to verify/create all tables
-- =====================================================

-- Step 1: Check existing tables
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- =====================================================
-- Step 2: Create/Verify studentProfile table
-- =====================================================
CREATE TABLE IF NOT EXISTS public."studentProfile" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supabase_user_id text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  suffix text,
  email text UNIQUE NOT NULL,
  contact_number text,
  year_level integer,
  program text,
  department text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true
);

-- =====================================================
-- Step 3: Create/Verify teacherProfile table
-- =====================================================
CREATE TABLE IF NOT EXISTS public."teacherProfile" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supabase_user_id text UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  middle_name text,
  suffix text,
  email text UNIQUE NOT NULL,
  contact_number text,
  id_number text UNIQUE,
  department text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean DEFAULT true
);

-- =====================================================
-- Step 4: Create/Verify addresses table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.addresses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house_number text,
  street_name text,
  subdivision text,
  barangay text,
  city text,
  province text,
  zip_code text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- =====================================================
-- Step 5: Create/Verify contacts table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name text,
  last_name text,
  middle_name text,
  suffix text,
  contact_number text,
  email text,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- =====================================================
-- Step 6: Create/Verify student_addresses junction table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.student_addresses (
  student_id bigint NOT NULL,
  address_id bigint NOT NULL,
  address_type text DEFAULT 'current',
  is_primary boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (student_id, address_id),
  FOREIGN KEY (student_id) REFERENCES public."studentProfile"(id) ON DELETE CASCADE,
  FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE
);

-- =====================================================
-- Step 7: Create/Verify teacher_addresses junction table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.teacher_addresses (
  teacher_id bigint NOT NULL,
  address_id bigint NOT NULL,
  address_type text DEFAULT 'current',
  is_primary boolean DEFAULT true,
created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (teacher_id, address_id),
  FOREIGN KEY (teacher_id) REFERENCES public."teacherProfile"(id) ON DELETE CASCADE,
  FOREIGN KEY (address_id) REFERENCES public.addresses(id) ON DELETE CASCADE
);

-- =====================================================
-- Step 8: Create/Verify student_emergency_contacts junction table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.student_emergency_contacts (
  student_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  relationship text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (student_id, contact_id),
  FOREIGN KEY (student_id) REFERENCES public."studentProfile"(id) ON DELETE CASCADE,
  FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE
);

-- =====================================================
-- Step 9: Create/Verify teacher_emergency_contacts junction table
-- =====================================================
CREATE TABLE IF NOT EXISTS public.teacher_emergency_contacts (
  teacher_id bigint NOT NULL,
  contact_id bigint NOT NULL,
  relationship text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  PRIMARY KEY (teacher_id, contact_id),
FOREIGN KEY (teacher_id) REFERENCES public."teacherProfile"(id) ON DELETE CASCADE,
  FOREIGN KEY (contact_id) REFERENCES public.contacts(id) ON DELETE CASCADE
);

-- =====================================================
-- Step 10: Disable RLS on all profile tables (for development)
-- =====================================================
ALTER TABLE public."studentProfile" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."teacherProfile" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_emergency_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.teacher_emergency_contacts DISABLE ROW LEVEL SECURITY;

-- =====================================================
-- Step 11: Verify all tables exist
-- =====================================================
SELECT 
    table_name,
    (SELECT COUNT(*) FROM information_schema.columns WHERE table_name = t.table_name) as column_count
FROM information_schema.tables t
WHERE table_schema = 'public' 
  AND table_type = 'BASE TABLE'
  AND table_name IN (
    'studentProfile',
    'teacherProfile', 
    'addresses',
    'contacts',
    'student_addresses',
    'teacher_addresses',
    'student_emergency_contacts',
    'teacher_emergency_contacts',
    'users',
    'roles',
    'user_roles'
  )
ORDER BY table_name;

-- =====================================================
-- Step 12: Check for any existing data
-- =====================================================
SELECT 'studentProfile' as table_name, COUNT(*) as record_count FROM public."studentProfile"
UNION ALL
SELECT 'teacherProfile', COUNT(*) FROM public."teacherProfile"
UNION ALL
SELECT 'addresses', COUNT(*) FROM public.addresses
UNION ALL
SELECT 'contacts', COUNT(*) FROM public.contacts
UNION ALL
SELECT 'users', COUNT(*) FROM public.users
UNION ALL
SELECT 'roles', COUNT(*) FROM public.roles
UNION ALL
SELECT 'user_roles', COUNT(*) FROM public.user_roles;

-- =====================================================
-- NOTES:
-- =====================================================
-- After running this script:
-- 1. All necessary tables should be created
-- 2. RLS is disabled for easier development
-- 3. Foreign keys are set up with CASCADE delete
-- 4. You should see the count of tables and their records
-- 
-- If you want to enable RLS for production, run the policies
-- from the Database_Setup.sql file
-- =====================================================
