-- =====================================================
-- COMPLETE DATABASE SETUP FOR STUDENT/TEACHER REGISTRATION
-- FIXED: Uses numeric role IDs instead of roleProfile strings
-- =====================================================
-- Run this SQL in your Supabase SQL Editor
-- =====================================================

-- Step 1: Create departments table (if not exists)
CREATE TABLE IF NOT EXISTS public.departments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departmentName" text NOT NULL,
  "departmentCode" text NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Step 2: Create programs table (if not exists)
CREATE TABLE IF NOT EXISTS public.programs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "programName" text NULL,
  "programCode" text NULL,
  "departmentId" bigint NULL,
  CONSTRAINT programs_departmentId_fkey FOREIGN KEY ("departmentId") REFERENCES departments (id)
);

-- Step 3: Insert sample departments
INSERT INTO public.departments (id, "departmentName", "departmentCode") VALUES 
    (1, 'Computer Science Department', 'CS'),
    (2, 'Information Technology Department', 'IT'),
    (3, 'Engineering Department', 'ENG'),
    (4, 'Business Administration Department', 'BA')
ON CONFLICT (id) DO NOTHING;

-- Step 4: Insert sample programs
INSERT INTO public.programs (id, "programName", "programCode", "departmentId") VALUES 
    (1, 'Bachelor of Science in Computer Science', 'BSCS', 1),
    (2, 'Bachelor of Science in Information Technology', 'BSIT', 2),
    (3, 'Bachelor of Science in Computer Engineering', 'BSCpE', 3),
    (4, 'Bachelor of Science in Information Systems', 'BSIS', 2)
ON CONFLICT (id) DO NOTHING;

-- Step 5: Create/verify roles table
CREATE TABLE IF NOT EXISTS public.roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "roleName" text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "roleProfile" text NULL
);

-- Step 6: Insert roles (roleProfile can be anything or null)
INSERT INTO public.roles (id, "roleName", "roleProfile") VALUES 
  (1, 'Student', '1'),
    (2, 'Teacher', '2'),
 (3, 'Admin', '3')
ON CONFLICT (id) DO NOTHING;

-- Step 7: Create/verify users table
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstName" text NOT NULL,
  email text NULL,
  "lastName" text NULL,
  "middleName" text NULL,
  suffix text NULL,
  "contactNumber" text NULL,
  "userTypeId" text NULL UNIQUE,  -- Supabase Auth UUID
  "isActive" boolean NULL DEFAULT true,
  "profilePictureUrl" text NULL,
  address text NULL,
"emergencyContact" text NULL,
  CONSTRAINT users_userTypeId_key UNIQUE ("userTypeId")
);

-- Step 8: DROP old user_roles table and recreate with correct schema
DROP TABLE IF EXISTS public.user_roles CASCADE;

CREATE TABLE public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "userId" text NOT NULL UNIQUE,  -- References users.userTypeId
  "roleId" bigint NOT NULL,  -- CHANGED: Now references roles.id (numeric)
  CONSTRAINT user_roles_userId_key UNIQUE ("userId"),
  CONSTRAINT user_roles_roleid_fkey FOREIGN KEY ("roleId") REFERENCES roles (id),
  CONSTRAINT user_roles_userId_fkey FOREIGN KEY ("userId") REFERENCES users ("userTypeId")
);

-- Step 9: Create/verify studentProfile table
CREATE TABLE IF NOT EXISTS public."studentProfile" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "studentId" text NULL,  -- References users.userTypeId
  "yearLevel" integer NULL,
  "programId" bigint NULL,-- FK to programs table
  "departmentId" bigint NULL,  -- FK to departments table
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT studentProfile_studentId_fkey FOREIGN KEY ("studentId") REFERENCES users ("userTypeId"),
  CONSTRAINT studentProfile_programId_fkey FOREIGN KEY ("programId") REFERENCES programs (id),
  CONSTRAINT studentProfile_departmentId_fkey FOREIGN KEY ("departmentId") REFERENCES departments (id)
);

-- Step 10: Create/verify teacherProfile table
CREATE TABLE IF NOT EXISTS public."teacherProfile" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departmentId" bigint NULL,  -- FK to departments table
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  "teacherId" text NULL,-- References users.userTypeId
  CONSTRAINT teacherProfile_teacherId_fkey FOREIGN KEY ("teacherId") REFERENCES users ("userTypeId"),
  CONSTRAINT teacherProfile_departmentId_fkey FOREIGN KEY ("departmentId") REFERENCES departments (id)
);

-- Step 11: Disable RLS for development (IMPORTANT!)
ALTER TABLE public.departments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.programs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."studentProfile" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."teacherProfile" DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public."emergencyContact" DISABLE ROW LEVEL SECURITY;  -- Changed from contacts

-- Step 12: Verify setup
SELECT 'Departments' as table_name, COUNT(*) as record_count FROM public.departments
UNION ALL
SELECT 'Programs', COUNT(*) FROM public.programs
UNION ALL
SELECT 'Roles', COUNT(*) FROM public.roles
UNION ALL
SELECT 'Users', COUNT(*) FROM public.users
UNION ALL
SELECT 'User Roles', COUNT(*) FROM public.user_roles
UNION ALL
SELECT 'Student Profiles', COUNT(*) FROM public."studentProfile"
UNION ALL
SELECT 'Teacher Profiles', COUNT(*) FROM public."teacherProfile";

-- Step 13: Show sample data
SELECT * FROM public.departments ORDER BY id;
SELECT * FROM public.programs ORDER BY id;
SELECT * FROM public.roles ORDER BY id;

-- =====================================================
-- KEY CHANGE: user_roles.roleId is now BIGINT
-- =====================================================
-- Now user_roles.roleId references roles.id (1, 2, 3)
-- The app will lookup role by name and get the ID:
--   - "Student" ? id = 1
--   - "Teacher" ? id = 2
--   - "Admin" ? id = 3
-- 
-- roleProfile can remain as "1", "2", "3" or be set to null
-- It's no longer used by the foreign key
-- =====================================================
